In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
X = iris.data 
y = iris.target

In [3]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
X_train

array([[  1.54399532e-02,  -1.19254753e-01,   2.25126850e-01,
          3.56381749e-01],
       [ -9.98450310e-02,  -1.04039491e+00,   1.13559562e-01,
         -2.86480506e-02],
       [  1.05300481e+00,  -1.19254753e-01,   9.50314227e-01,
          1.12644135e+00],
       [ -1.36797986e+00,   3.41315328e-01,  -1.39259884e+00,
         -1.31208072e+00],
       [  1.16828980e+00,   1.11030287e-01,   7.27179649e-01,
          1.38312788e+00],
       [ -1.02212490e+00,   1.03217045e+00,  -1.22524790e+00,
         -7.98707650e-01],
       [ -5.60984968e-01,   1.49274053e+00,  -1.28103155e+00,
         -1.31208072e+00],
       [ -1.02212490e+00,  -2.42210516e+00,  -1.65358660e-01,
         -2.85334584e-01],
       [  7.07149859e-01,  -1.19254753e-01,   9.50314227e-01,
          7.41411549e-01],
       [  9.37719827e-01,   5.71600368e-01,   1.06188152e+00,
          1.63981441e+00],
       [  1.30724937e-01,  -1.96153508e+00,   6.71396005e-01,
          3.56381749e-01],
       [  9.37719827e

In [7]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components = 2, kernel = 'rbf')
X_train2 = kpca.fit_transform(X_train)
X_test2 = kpca.transform(X_test)

In [8]:
kpca

KernelPCA(alpha=1.0, coef0=1, copy_X=True, degree=3, eigen_solver='auto',
     fit_inverse_transform=False, gamma=None, kernel='rbf',
     kernel_params=None, max_iter=None, n_components=2, n_jobs=1,
     random_state=None, remove_zero_eig=False, tol=0)

In [9]:
X_train2

array([[ -3.37725246e-01,  -2.67929399e-01],
       [ -2.28159618e-01,  -6.42964823e-01],
       [ -5.42657970e-01,   4.00470428e-01],
       [  7.68893086e-01,   4.93146060e-02],
       [ -4.94431455e-01,   4.74938667e-01],
       [  7.26835183e-01,   1.08946020e-01],
       [  6.93412746e-01,   1.93039625e-01],
       [  2.71518785e-02,  -4.56605659e-01],
       [ -5.56008764e-01,   2.08040974e-01],
       [ -4.15727350e-01,   5.35959232e-01],
       [ -2.33820327e-01,  -4.91624713e-01],
       [ -4.12615994e-01,  -2.79420859e-02],
       [ -1.42346326e-01,  -6.98291047e-01],
       [ -3.19744482e-01,   5.23774154e-01],
       [ -3.91565822e-01,   1.76538163e-01],
       [ -1.06099524e-01,  -7.01543477e-01],
       [ -5.02349236e-01,  -1.80419722e-01],
       [ -4.93355128e-01,  -1.85187916e-01],
       [ -1.27684052e-01,  -5.40426177e-01],
       [ -4.25423269e-01,  -2.48918261e-01],
       [ -3.99211444e-01,   2.72605297e-01],
       [ -5.58726954e-01,   2.40347780e-01],
       [ -

In [ ]:
ICA = FastICA(n_components=2, random_state=12,whiten= True) 
X=ICA.fit_transform(X_train.values)